apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: &app rancher
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: rancher-values
  namespace: *app
  files:
  - values.yaml
resources:
- helmrelease.yaml
- namespace.yaml