hostname: rancher.homelab

systemDefaultRegistry: harbor.homelab/docker-proxy-cache

service:
  disableHTTP: false

ingress:
  enabled: true
  includeDefaultExtraAnnotations: false
  extraAnnotations:
    cert-manager.io/cluster-issuer: homelab-ca
    cert-manager.io/common-name: rancher.homelab
  ingressClassName: "traefik"

  pathType: ImplementationSpecific
  path: "/"

  # If setting service.disableHTTP=true, set ingress.servicePort=80
  servicePort: 80
  tls:
    source: secret
    secretName: rancher-tls

# Set agent mode to not use strict TLS for homelab
agentTLSMode: "system-store"

# Don't use a private CA cert for homelab
privateCA: false