hostname: rancher.homelab

systemDefaultRegistry: harbor.homelab/docker-proxy-cache

service:
  disableHTTP: true

ingress:
  enabled: true
  includeDefaultExtraAnnotations: false
  extraAnnotations:
    cert-manager.io/cluster-issuer: homelab-ca
    cert-manager.io/common-name: rancher.homelab
  ingressClassName: "traefik"

  pathType: ImplementationSpecific
  path: "/"
  servicePort: 443
  tls:
    source: secret
    secretName: rancher-tls
