hostname: rancher.homelab

systemDefaultRegistry: harbor.homelab/docker-proxy-cache

service:
  disableHTTP: false

ingress:
  enabled: true
  ingressClassName: "traefik"

# Agent TLS Mode ('strict' or 'system-store')
agentTLSMode: "strict"