apiVersion: v1
kind: Secret
metadata:
    name: homepage-values-secret
    namespace: homepage
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:xZxnySrRUNgFmrMMsROkGeffOukeQstv+PTc6sF1VlMUKN3k2JPVlQNhpOaPHdb3yJBFF/86foD1EJVX3YOXbM3yPUpDl4HLMVHPYMD5fMzkblHUl73sMTBYxogs5hS3jrlkCLFCuUn5XytwArhlX7rLTEak4oOQDUn2vDVDzcjjg1byrH8RuSGGU+Q84D6gCbKNRxrQ5C3GF1cf3A7f4u+8iO94xVIuDJrgv7OchohwSYHje5m9Oz4sIw9EXsuppcZ72BoH1MNtGPQgcNPy05qkBDCnGTtsVJuGt2pj2o1rxZzhhmgz9E+H1WzuUbmIbwxz6bIKLRG8QrcCdD+1Rcm9QTAoJReKh/YhTAJ2YsgtYImzx/0mUbxXkBb1nxAHPJwjbYNptvkxRY+WB34d/nOeBPKZdQoBZCExOEGD3mdbar1uYW0dLrqrg/XIRZJLhB2MCASSfbeN4Wzf3XpZkW6HuqwIQePvx3QMWXkW6xm91FKYyrazxqgL5pXjHnjUw5SOuobw2mnwoFeG6MsPSY84N1etUamcd4QNpr51jpEMI8CDMcnUIoBouhGEDh2zsDsD8Cmh3SymOrQ2h/jhfUCSHZEcb6q+aEQT8dWw7Ua0Ty8ENBOhIxhP1lk8/PHvkFH12PRMKZjW6ioluPSaGNV0VUHNb5A/PaFV49aGpkt7R8CTvjw0Rk2xqyYH6rrtJin92ucvNctAn6LWnG411cp2tq7NiL4jJ2oGqT5Sz7kORulwZUFGTgFXCQGnbNQi7J9EnHhmLIQ+s3U4eFTzfPGmUPnhDGGcRbc/hy7xRppz16oNnlxzPBMvI6yGALT54CF6LPm4yGgRwC1j0IhY513KAm9bGYbkyOvbpSpJmnEZnl1HnYCpRyvYnyfNI5JtQWs5BKsGgBltmNpQHS2heQ4vlgojGuLtw2xgreu7UMoAe28ZvfF1H8hH9KTCVtRv8GK7a1sjJeqTkCFVrOZtPFyPNnfYeY+qiLfyumjDv7686g+ivZPCCg3mE8mNt1FyT6IIRhJjGh8l0laejfVV8jGPaOLirPMRzMGxFV1R9L1W7wOovORLKGLbYGfLdajIe+B/zTRhjURUO0IdWRB93UpfWJG+PagtabXaKUyZDWGNQQ9AM+9PfXgRv+jMlF+QCV+ctbWwz+zr+wZ17Ss0bBtX89Hn2HnOiFeq7tl1UKAIqjcXHv7ZlEApFtq3zA/Ic/TvZX4WYH7DgJfQacZxbTm+CbmKFkFRW7hnZKkR25kn7vFWVpF2SodguEfmGJMP4tS+h24uh7uP7hiYo1qTwMSRzp4pylUnUVRgOKJ78TeUOUVWsHDAtXjkS+LVuJudhdatTnYiqBcYWYo+xznvabAyzm9aGNXLiQmVasozPU1FQUHxVRT5tuVEsmQPEfz6+kBIj+1zmxroJqS0Yd5wzYJDQY+9Xwsvcm1JzcZKg1S+VNg6foh+5CmDb1XejPbeHV9wSEqT3nzxr3VgeIWmw3K4KQAZgodPty5cIOE2SqMUdGIcZZelO0fjFIe1fwqx3YwCByqTOaqSDTviBc/PDtzELtnWZNdUVnZtR9POFFo/FS1zGFAOiQ0UlpIMk7lrR5SpeNlhW0SMoPug2nAip0jiJdyb/2fHSfLagnP25nTDzHFdrMga0UzPpVPGuDXpdX5an7ykmxEbSobDV4j49f58UcT3uavF+mycWUj9Jk/3quOMbl5QxZPv2vMHEDACGpFee+jA9gwX+Y3IPfn5FxXI5cBcZ3TH1kJdFVfZBpffG/IUZvDAv+WmtuMSgXzM1a4/99+eI90mBD/Dp3uZgsEUjUijk6nEGD+UpNaXFtqUdgm3fGRL+oewvp/GVqNc8hLMIO5WpAf8aDqBXnLlnPiQjIjxiPVJwDlhFwp+b2iMqstjavhu0UoXPt4ahSVOViX5kJWyFKMfPJW7VmUpIvhiF8IgtuzPLcepTjV99AaYe4ZmrisLqjlKoJlgvO+D5nW9eTfKQgaxyeHyNqkfX2oZmmAbTrxCKycoEUsdaQM5cT1OxZ0L88Xd31IPgoANCh3JdcQli0gEuwzYCiWCNGktvcO4qy3ST/b1DMWaeX18q9DL3zBPujnH+rzWZQoMHDvrRIh0u486j2vPWtOVYR6MEl7Oz3BPXQUCW4ACRQGaEN1mS8AcrEpkzXobDviVcWtghcNRfZkCU3po4qePBX6jdnQoxumGToAw2NSQGIQSlZWrp43Cv0d+6VSXVxU1LqKGW10HEoEt8h9++1thhaHui/ZNU72/P71Fw5lpid9Ds2PqGtc0q6e82ZPX4a77mIQ/ZZC6+exZE4uc5hwatJ/1jHQ0mDRgWkE7LzaGW64eVtOPdfL/xAOtX1EZnXmiZp701k2XdS2GYfbu,iv:697OqFYUTPkHEgnfjYBjZgktBtvZ8X3vz9LWd0dhKcM=,tag:6mIbNA1mHUJhVTLUxWcRZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-01-18T05:13:49Z"
    mac: ENC[AES256_GCM,data:gV2RkdcqME9nG3cR3NxRPnH9ooDLXfc02v8we67GFGTXxLJF83HNVhiItDpaY4qNNoGBCSzGS74rCewDSp5XfZ7D3ER3QquRGkll1UJjdmzMqw9O6wiVmB1JRymACHiVw43ck/d5SqKL081zu2/l2sbPTarudESKE6GjDt09818=,iv:lpMiVkPFaaAQ9Iacm+1Y3p+1td9Krs9+H/NyOWy1U0M=,tag:xebtFoAmCUpx8WEsoVNHgg==,type:str]
    pgp:
        - created_at: "2026-01-18T05:13:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAybZwhlimvyVARAAhAgvZCviEEZTI07fTUBc0eUGAribWdP+aEduZmE0JyWL
            ilPmXutOHyFqSeeXsCC0MxqNcWJgedbT7DyT+yjK9JypuuFXZutB4iZ7uhuZxPOK
            p1mk6sbzyMV4T/HWrm+JS93TDfkwee0T0eZ+zXec1fRUqaTjXRWZiLupZxINwkHR
            fK7HYdNkxtjm3Uw0o27MwIw9x42amVitWravXwrsLyF9XCQA+WG6Rd7j2LFZVhzn
            wBOkvwZsgms4sBlGcOo59hC4yHsB5fRWfJPJ/5lVGTiedX7Yj3mzSZfoN8JQLRv5
            b3Mf98V1PobPU5pCUOuhm76AYI13NJf0Iph6yKcLEzUCfpP0QRf3/3fS9Y798VFc
            CJK2utFtt+Fsms2W+AMXtCDhTd181JAQ75m9kFMix4XgJTXy49Vvyivt3UA89FK7
            gviK/tVSaOnN1w+GeVu2PLiO2yn9GNKAJcn8lOiLKitgK07VU9tubMoWNGtuk6xZ
            9McCUjWSih8SPpOwQq4tGMurm3/SKrS9iUmKGJUCEw7PfqUMPMityPoi2BSjCGKv
            h+ZAZQVMD8fd4T9jUj1RoOmSMW5Ea946d4E0LMiIHsDs6N1tD2SW2BvrP+8NPwiE
            q531rpgmuc+S5ECfgZRLjp4ODbSEV/0uqZDrlvDFqzJuZQRX2M15aZbEaIa+9crU
            ZgEJAhDdhtz1VVrx+pDNxEn+567aFHkpF8dlq/wSkl/cgrhFNnExDaqOkT35Q/E9
            9JerWpTVQwptLgJIn48ZZ9RXbiww3xFtwf0cz88Bb6SqxsFlGM+hEVOI9fDKyoDI
            pNau032mHQ==
            =nlbK
            -----END PGP MESSAGE-----
          fp: 61026EB60835C9F13F6A9990B754BDB32786572A
    encrypted_regex: ^(data|stringData|env|password|token|username|email|auth|clientSecret|accessKey|href)$
    version: 3.9.1
