apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: homepage-values
  namespace: homepage
  files:
  - values.yaml
resources:
- helmrelease.yaml
- homepage-values-secret.sops.yaml
- namespace.yaml