image:
    repository: harbor.homelab/ghcr-proxy-cache/gethomepage/homepage
    tag: latest

serviceAccount:
    create: true
    name: homepage

enableRbac: true

config:
    settings:
        disableHostValidation: true
        theme: dark
        color: neutral
        background: 
          image: https://images.unsplash.com/photo-1623180921692-204e49f5a34e?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
        #   blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
          saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
          brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
          opacity: 50 # 0-100

    bookmarks:
        - AI Platforms:
            - ChatGPT:
                - icon: chatgpt.svg
                  abbr: CG
                  href: https://chatgpt.com
            - GROK:
                - icon: grok.svg
                  abbr: GK
                  href: https://grok.com
                
        - Developer:
            - Github:
                - icon: github.svg
                  abbr: GH
                  href: https://github.com/
                  
        - Entertainment:
            - YouTube:
                - icon: youtube.svg
                  abbr: YT
                  href: https://youtube.com/
            - Rumble:
                - icon: rumble.svg
                  abbr: RB
                  href: https://rumble.com/
            - Spotify:
                - icon: spotify.svg
                  abbr: SP
                  href: https://open.spotify.com/
            - SoundCloud:
                - icon: soundcloud.svg
                  abbr: SC
                  href: https://soundcloud.com/
    kubernetes:
        mode: cluster

ingress:
    main:
        enabled: true
        annotations:
            cert-manager.io/cluster-issuer: homelab-ca
        hosts:
            - host: homepage.homelab
              paths:
                - path: /
                  pathType: Prefix
        tls:
            - hosts:
                - homepage.homelab
              secretName: homepage-tls
