apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: minio-tenant-values
  namespace: minio-tenant
  files:
  - values.yaml
resources:
- helmrelease.yaml
- namespace.yaml
- minio-tenant-secret.sops.yaml
