tenant:
  name: harvester-minio

  configuration:
    name: minio-tenant-secret

  configSecret:
    existingSecret: true
    name: minio-tenant-secret

  poolsMetadata:
    labels: 
      harvester-minio: "true"

  pools:
  - servers: 1
    name: pool-0
    volumesPerServer: 1
    size: 20Gi

ingress:
  console:
    enabled: true
    ingressClassName: "nginx"
    labels:
      minio-tenant: harvester
    annotations:
      cert-manager.io/cluster-issuer: homelab-ca
    tls:
      - hosts:
          - minio.homelab
        secretName: minio-console-tls
    host: minio.homelab
    path: /
    pathType: Prefix
