apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rustfs
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: rustfs-values
  namespace: rustfs
  files:
  - values.yaml
resources:
- helmrelease.yaml
- namespace.yaml
- rustfs-credentials-secret.sops.yaml