apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: harbor
configMapGenerator:
- name: harbor-values
  namespace: harbor
  files:
  - values.yaml
resources:
- helmrelease.yaml
- namespace.yaml
